# Generated by Django 6.0.2 on 2026-02-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('iD', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('iD', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('iD', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('iD', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('action', models.TextField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_UserStory', to='rex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('iD', models.AutoField(primary_key=True, serialize=False)),
                ('userStories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userStory_Epic', to='rex.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalRequirement',
            fields=[
                ('requirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rex.requirement')),
                ('epics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='epic_FunctionalRequirement', to='rex.epic')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='testCase_FunctionalRequirement', to='rex.testcase')),
            ],
            bases=('rex.requirement',),
        ),
        migrations.CreateModel(
            name='BusinessRules',
            fields=[
                ('requirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rex.requirement')),
                ('frs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionalRequirement_BusinessRules', to='rex.functionalrequirement')),
            ],
            bases=('rex.requirement',),
        ),
        migrations.CreateModel(
            name='NonFunctionalRequirement',
            fields=[
                ('requirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rex.requirement')),
                ('frs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionalRequirement_NonFunctionalRequirement', to='rex.functionalrequirement')),
            ],
            bases=('rex.requirement',),
        ),
    ]
